# Generated by Django 4.2.4 on 2023-09-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAcoount', '0006_remove_user_post_ofice_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='is_applicant',
            field=models.BooleanField(default=False),
        ),
    ]
