# Generated by Django 4.2.4 on 2023-09-04 17:42

import UserAcoount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAcoount', '0008_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=UserAcoount.models.upload_to_user_profile_image),
        ),
    ]
