# Generated by Django 4.2.4 on 2023-09-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAcoount', '0010_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
