# Generated by Django 4.2.4 on 2023-09-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAcoount', '0012_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
