# Generated by Django 4.2.4 on 2023-10-03 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserAcoount', '0019_remove_organizationuser_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
